# Generated by Django 5.2.4 on 2025-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_items_alter_item_currency_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(default=123),
            preserve_default=False,
        ),
    ]
