# Generated by Django 5.2.4 on 2025-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_discount_amount_remove_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('rub', 'рубль'), ('usd', 'доллар')], default='rub'),
        ),
        migrations.AddField(
            model_name='tax',
            name='currency',
            field=models.CharField(choices=[('rub', 'рубль'), ('usd', 'доллар')], default='rub'),
        ),
    ]
